// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsd4JkCk_PWQWpMrTS7l9t_b__cdIGE_Y',
    appId: '1:480235726199:web:78f7d45c0dc525bce66d72',
    messagingSenderId: '480235726199',
    projectId: 'twitter-clone-2753a',
    authDomain: 'twitter-clone-2753a.firebaseapp.com',
    storageBucket: 'twitter-clone-2753a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJw6Gb0FhNh4o-G-gSLWwOi5khW-g_GfA',
    appId: '1:480235726199:android:9f1ebfaa988020a0e66d72',
    messagingSenderId: '480235726199',
    projectId: 'twitter-clone-2753a',
    storageBucket: 'twitter-clone-2753a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoGqngR8U8eOGea3K65ZhGZiUQWZqkOLo',
    appId: '1:480235726199:ios:59732ad100dc820ae66d72',
    messagingSenderId: '480235726199',
    projectId: 'twitter-clone-2753a',
    storageBucket: 'twitter-clone-2753a.appspot.com',
    iosBundleId: 'com.example.twitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoGqngR8U8eOGea3K65ZhGZiUQWZqkOLo',
    appId: '1:480235726199:ios:3681f7ca1dda0345e66d72',
    messagingSenderId: '480235726199',
    projectId: 'twitter-clone-2753a',
    storageBucket: 'twitter-clone-2753a.appspot.com',
    iosBundleId: 'com.example.twitter.RunnerTests',
  );
}
